version: '2.2'

services:
  elasticsearch:
    image: elasticsearch:5.6
    restart: always
    networks:
      conductor-boot-nw:
        aliases:
          - elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:9200/_cat/health"]
      interval: 120s
      timeout: 30s
      retries: 10
    mem_limit: "3096000000"
    #volumes:
      #- es_data:/var/lib/elasticsearch
  database:
    image: mysql:5.7
    restart: always
    networks:
      conductor-boot-nw:
        aliases:
          - mysql_db
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: conductor
      MYSQL_USER: conductor
      MYSQL_PASSWORD: Conductor@1234
      MYSQL_INITDB_SKIP_TZINFO: NONE
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 120s
      timeout: 30s
      retries: 15
    mem_limit: "512000000"
      #volumes:
        #- db_data:/var/lib/mysql
  #database:
      #    image: mariadb:latest
      #    restart: always
      #    networks:
      #      conductor-boot-nw:
      #        aliases:
      #          - mysql_db
      #    ports:
      #      - 3306:3306
      #      - 33060:33060
      #    environment:
      #      MYSQL_ROOT_PASSWORD: Root@1234
      #      MYSQL_DATABASE: conductor
      #      MYSQL_USER: conductor
      #      MYSQL_PASSWORD: Conductor@1234
      #      MYSQL_INITDB_SKIP_TZINFO: NONE
      #    healthcheck:
      #      test: ["CMD-SHELL", 'mysqladmin ping']
      #      interval: 120s
      #      timeout: 30s
      #      retries: 15
      #    mem_limit: "512000000"
    #volumes:
      #- db_data:/var/lib/mysql
  conductor-boot:
    image: conductor-boot:latest
    build:
      context: .
    restart: always
    depends_on:
      - database
      - elasticsearch
    networks:
      conductor-boot-nw:
        aliases:
          - conductor-boot
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE_HOST: mysql_db
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE: conductor
      MYSQL_USER: conductor
      MYSQL_PASSWORD: Conductor@1234
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      SPRING_PROFILES_ACTIVE: basic,mysql,external-elasticsearch,embedded-oauth2,security,conductor
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/api/health"]
      interval: 60s
      timeout: 30s
      retries: 15
    mem_limit: "1536000000"
#volumes:
  #  es_data:
  #    driver: local
  #    driver_opts:
  #      type: none
  #      device: $PWD/container/persistence/elasticsearch
  #      o: bind
  #  db_data:
  #    driver: local
  #    driver_opts:
  #      type: none
  #      device: $PWD/container/persistence/mysql
  #      o: bind
networks:
  conductor-boot-nw:
