ELASTICSEARCH_HOST: localhost
ELASTICSEARCH_PORT: 9200

# Use embedded/persistence to have a common persistence location for all embedded components.
# Default is NONE
ELASTICSEARCH_DATA_DIR: embedded/persistence

# Use embedded/resources to have a common resources location for all embedded components.
# Default is NONE
ELASTICSEARCH_RESOURCE_DIR: NONE

elasticsearch:
  type: SPRING_BOOT_EMBEDDED
  version: 5.5.2
  resource:
    binary:
      path: ${ELASTICSEARCH_RESOURCE_DIR}/elasticsearch-${elasticsearch.version}
      name: elasticsearch-${elasticsearch.version}.zip
  dir: ${ELASTICSEARCH_DATA_DIR}
  startup:
    time-out: 60
  http:
    port: ${ELASTICSEARCH_PORT}
  tcp:
    port: 9300
  cleanInstallationDirectoryOnStop: false

workflow:
  elasticsearch:
    cluster:
      health:
        color: yellow
    version: 5
    instanceType: EXTERNAL
    url: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    index:
      name: conductor
    tasklog:
      index:
        name: task_log

management:
  endpoint:
    health:
      show-details: always
      elasticsearch:
        enabled: true