server:
  port: 8080
  use-forward-headers: true
  ssl:
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: classpath:keystore/my.p12
    # The password used to generate the certificate
    key-store-password: conductor
    # The alias mapped to the certificate
    key-alias: my
    enabled: false

spring:
  liquibase:
    enabled: false
  application:
    name: Conductor Boot Wrapper

awaitTermination: 120

# Deprecated
security:
  basic:
    enabled: false

oauth:
  security: NONE

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  write:
    level: INFO
  format:
    style: splunk
  exclude: [/, /actuator/**, /v3/api-docs/**, /swagger-ui/**, /index.html, /images/**, /swagger-ui.js, /lib/**, /css/**, /api/swagger.json, /api/health]
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
    parameters:
      - access_token
      - password

zuul:
  add-proxy-headers: true
  add-host-header: true
  ssl-hostname-validation-enabled: false
  sensitive-headers:
    - Authorization