flyway:
  enabled: true

conductor:
  server:
    startup:
      enabled: true
  jetty:
    server:
      port: 1987
  mysql:
    connection:
      timeout: 18000000
      idle:
        timeout: 31536000
      pool:
        idle:
          min: 2
        size:
          max: 10000
  additional:
    modules: com.netflix.conductor.contribs.ArchivingWorkflowModule

zuul:
  routes:
    conductor-index:
      path: /
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
    conductor-html:
      path: /index.html
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-json:
      path: /api/swagger.json
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-images:
      path: /images/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-lib:
      path: /lib/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-css:
      path: /css/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-js:
      path: /swagger-ui.js
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-api:
      path: /api/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
