ADFS_CLIENT_ID: ABCD-1234_CLIENT
ADFS_RESOURCE: ABCD-1234_RESOURCE
ADFS_HOST: idm.github.maheshyaddanapudi.com

oauth:
  security: ADFS

security:
  oauth2:
    client:
      clientId: $ADFS_CLIENT_ID
      userAuthorizationUri: https://$ADFS_HOST/adfs/oauth2/authorize?resource=$ADFS_RESOURCE
      accessTokenUri: https://$ADFS_HOST/adfs/oauth2/token
      tokenName: code
      authenticationScheme: query
      clientAuthenticationScheme: form
      grant-type: authorization_code
    resource:
      userInfoUri: https://$ADFS_HOST/adfs/oauth2/token
