MYSQL_DATABASE: conductor
MYSQL_USER: conductor
MYSQL_PASSWORD: conductor

# This directory has to be explicitly set to let Embedded MariaDB know the master persistence location.
# Use embedded/persistence/mariadb4j to have a common persistence location for all embedded components.
# Default is NONE
MARIADB4J_DIR: NONE

spring:
  datasource:
    name: ${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

wrapper_db: mariadb4j

# If dataDir, libDir & baseDir are not set, then the database will not be persistent.
mariadb4j:
  dataDir: ${MARIADB4J_DIR}/data
  libDir: ${MARIADB4J_DIR}/lib
  baseDir: ${MARIADB4J_DIR}/base
  port: 0
  maxConnections: 100000
  wait:
    timeout: 18000000
  connect:
    timeout: 31536000
  deleteBaseAndDataDirOnShutdown: false
  security:
    disabled: true

flyway:
  validate-on-migrate: false
  baseline-on-migrate: false
  ignore-missing-migrations: true