ELASTICSEARCH_HOST: localhost
ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_VERSION: 5
ELASTICSEARCH_URL: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

# ES Props
elasticsearch:
  type: EXTERNAL

workflow:
  elasticsearch:
    cluster:
      health:
        color: yellow
    version: ${ELASTICSEARCH_VERSION}
    instanceType: EXTERNAL
    index:
      name: conductor
    tasklog:
      index:
        name: task_log

management:
  health:
    elasticsearch:
      enabled: true