ADFS_CLIENT_ID: ABCD-1234_CLIENT
ADFS_RESOURCE: ABCD-1234_RESOURCE
ADFS_USER_AUTHORIZATION_URL: https://adfs.example.com/adfs/oauth2/authorize
ADFS_ACCESS_TOKEN_URL: https://adfs.example.com/adfs/oauth2/token
ADFS_USER_INFO_URL: https://adfs.example.com/adfs/oauth2/authorize

oauth:
  security: ADFS

security:
  oauth2:
    client:
      clientId: ${ADFS_CLIENT_ID}
      userAuthorizationUri: ${ADFS_USER_AUTHORIZATION_URL}?resource=${ADFS_RESOURCE}
      accessTokenUri: ${ADFS_ACCESS_TOKEN_URL}
      tokenName: code
      authenticationScheme: query
      clientAuthenticationScheme: form
      grant-type: authorization_code
    resource:
      userInfoUri: ${ADFS_USER_INFO_URL}
